Fixed schemas and added row transform function
singer-io/tap-gemini pull request #2
Opened 2019-08-16 14:34 UTC by Joe-Heffer-MPE

This has been tested (all schemas) with target-csv.

2019-08-16 14:34 UTC, cmerrick commented
Hi @Joe-Heffer-MPE, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

2019-08-16 14:38 UTC, cmerrick commented
You did it @Joe-Heffer-MPE!

Thank you for signing the Singer Contribution License Agreement.

2019-08-28 10:33 UTC, Joe-Heffer-MPE commented
Is there any feedback on this pull request?

Thanks

2019-08-28 13:52 UTC, luandy64 requested changes
I'll merge this since this is still in alpha, but I think the `setup.py` changes need to be made first

2019-08-28 13:52 UTC, luandy64 commented on setup.py
> +        "pytz",
```suggestion
        "singer-python==5.4.1",
        "requests==2.21.0",
        "pytz==2018.4",
```

2019-08-28 13:52 UTC, luandy64 commented on setup.py
> +        "pytz",
We want to keep the pinned versions, but the `=` is a syntax error

2019-08-28 13:52 UTC, luandy64 commented on tap_gemini/__init__.py
> +    return cast_date_to_datetime(date=datetime.date.today())
This function seems redundant. You could just have
```
def cast_date_to_datetime(date: datetime.date = datetime.date.today()) -> datetime.datetime:
```

2019-10-21 13:31 UTC, Joe-Heffer-MPE commented
Hi, I've made the changes discussed above and merged the changes onto the master branch on Joe-Heffer-MPE/tap-gemini.

2019-10-22 09:00 UTC, Joe-Heffer-MPE commented
I've made changes and tested the full integration (i.e. full historic replication) by piping the data into target-csv using Windows and Linux environments. I've pushed the changes to master on https://bitbucket.org/Joe_Heffer/tap-gemini

2019-10-29 20:32 UTC, dmosorast commented
Closing this, handled in #3.

PR #3 rebased these changes onto a new branch and pulled a merge commit from bitbucket/Joe_Heffer/master.

2019-10-29 20:32 UTC, closed without merging